<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPZYCc8c\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPZYCc8c/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPZYCc8c.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPZYCc8c\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPZYCc8c\App_KernelProdContainer([
    'container.build_hash' => 'PZYCc8c',
    'container.build_id' => '6de6c8d4',
    'container.build_time' => 1771745331,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPZYCc8c');
