<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbortEmailMarketingService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\Service\RecordActions\AbortEmailMarketing' shared autowired service.
     *
     * @return \App\Process\Service\RecordActions\AbortEmailMarketing
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/RecordActions/AbortEmailMarketing.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Process\\Service\\RecordActions\\AbortEmailMarketing'])) {
            return $container->privates['App\\Process\\Service\\RecordActions\\AbortEmailMarketing'];
        }

        return $container->privates['App\\Process\\Service\\RecordActions\\AbortEmailMarketing'] = new \App\Process\Service\RecordActions\AbortEmailMarketing(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $a);
    }
}
