<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddEmailToQueueSchedulerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Service\Scheduler\Jobs\AddEmailToQueueScheduler' shared autowired service.
     *
     * @return \App\Schedulers\Service\Scheduler\Jobs\AddEmailToQueueScheduler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/SchedulerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/Scheduler/Jobs/AddEmailToQueueScheduler.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Queue/EmailQueueingServiceInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Queue/DefaultEmailQueueingService.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Targets/TargetProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/EmailTargetProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/DefaultEmailTargetProvider.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));
        $b = ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container));

        return $container->privates['App\\Schedulers\\Service\\Scheduler\\Jobs\\AddEmailToQueueScheduler'] = new \App\Schedulers\Service\Scheduler\Jobs\AddEmailToQueueScheduler(new \App\Module\Campaigns\Service\Email\Queue\DefaultEmailQueueingService($a, $b, ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService')), ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')), ($container->privates['App\\SystemConfig\\LegacyHandler\\LegacySettingsProvider'] ?? $container->load('getLegacySettingsProviderService')), ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueManager'] ?? $container->load('getDefaultEmailQueueManagerService')), new \App\Module\Campaigns\Service\Email\Targets\DefaultEmailTargetProvider($a, $b), ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\EmailTargetValidatorManager'] ?? $container->load('getEmailTargetValidatorManagerService')), ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Log\\DefaultEmailCampaignLogManager'] ?? $container->load('getDefaultEmailCampaignLogManagerService')), ($container->privates['App\\Module\\Campaigns\\Service\\EmailMarketing\\DefaultEmailMarketingManager'] ?? $container->load('getDefaultEmailMarketingManagerService'))));
    }
}
