<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttachmentFieldListApiMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Service\Fields\Attachments\Mappers\AttachmentFieldListApiMapper' shared autowired service.
     *
     * @return \App\Module\Service\Fields\Attachments\Mappers\AttachmentFieldListApiMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['App\\Module\\Service\\Fields\\Attachments\\Mappers\\AttachmentFieldListApiMapper'] = $container->createProxy('AttachmentFieldListApiMapperGhost1fcfeab', static fn () => \AttachmentFieldListApiMapperGhost1fcfeab::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseModuleMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseFieldTypeMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/ApiRecordMappers/ApiRecordFieldTypeMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Module/Service/Fields/Attachments/Mappers/AttachmentFieldApiMapperTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Module/Service/Fields/Attachments/Mappers/AttachmentFieldListApiMapper.php';

        return ($lazyLoad->__construct(($container->privates['App\\MediaObjects\\Repository\\DefaultMediaObjectManager'] ?? self::getDefaultMediaObjectManagerService($container)), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container))) && false ?: $lazyLoad);
    }
}
