<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadExtensionUploadValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\MediaObjects\Validator\UploadValidator\Validators\BadExtensionUploadValidator' shared autowired service.
     *
     * @return \App\MediaObjects\Validator\UploadValidator\Validators\BadExtensionUploadValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Validator/UploadValidator/UploadValidatorInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Validator/UploadValidator/Validators/BadExtensionUploadValidator.php';

        return $container->privates['App\\MediaObjects\\Validator\\UploadValidator\\Validators\\BadExtensionUploadValidator'] = new \App\MediaObjects\Validator\UploadValidator\Validators\BadExtensionUploadValidator(($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')));
    }
}
