<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignEmailParserManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Parser\CampaignEmailParserManager' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Parser\CampaignEmailParserManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Parser/CampaignEmailParserManager.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Parser/CampaignEmailParserMapperTrait.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Parser/CampaignEmailParserRegistry.php';

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\CampaignEmailParserManager'] = new \App\Module\Campaigns\Service\Email\Parser\CampaignEmailParserManager(new \App\Module\Campaigns\Service\Email\Parser\CampaignEmailParserRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\SurveyURLParser'] ?? $container->load('getSurveyURLParserService'));
            yield 1 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\TrackerHeaderParser'] ?? $container->load('getTrackerHeaderParserService'));
            yield 2 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\TrackerLinksParser'] ?? $container->load('getTrackerLinksParserService'));
            yield 3 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\UnsubscribeLinkParser'] ?? $container->load('getUnsubscribeLinkParserService'));
            yield 4 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\ViewedEmailTrackerParser'] ?? $container->load('getViewedEmailTrackerParserService'));
        }, 5)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
