<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckCronUserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Service\Installation\Steps\CheckCronUser' autowired service.
     *
     * @return \App\Install\Service\Installation\Steps\CheckCronUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Installation/InstallStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Installation/InstallStepTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Installation/Steps/CheckCronUser.php';

        $container->factories['service_container']['App\\Install\\Service\\Installation\\Steps\\CheckCronUser'] = function ($container) {
            return new \App\Install\Service\Installation\Steps\CheckCronUser(($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')));
        };

        return $container->factories['service_container']['App\\Install\\Service\\Installation\\Steps\\CheckCronUser']($container);
    }
}
