<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckDuplicateEmailService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Default\CheckDuplicateEmail' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Default\CheckDuplicateEmail
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/EmailTargetValidatorInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/BaseEmailTargetValidator.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/Validators/Default/CheckDuplicateEmail.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/EmailMarketingDuplicateCheckerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/DefaultEmailMarketingDuplicateChecker.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckDuplicateEmail'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckDuplicateEmail'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckDuplicateEmail'] = new \App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Default\CheckDuplicateEmail(new \App\Module\Campaigns\Service\Email\Targets\DefaultEmailMarketingDuplicateChecker($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))));
    }
}
