<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckEmailMarkedInvalidService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Default\CheckEmailMarkedInvalid' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Default\CheckEmailMarkedInvalid
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/EmailTargetValidatorInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/BaseEmailTargetValidator.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/Validators/Default/CheckEmailMarkedInvalid.php';

        $a = ($container->privates['App\\Emails\\Service\\Validation\\EmailValidationHelper'] ?? $container->load('getEmailValidationHelperService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckEmailMarkedInvalid'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckEmailMarkedInvalid'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckEmailMarkedInvalid'] = new \App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Default\CheckEmailMarkedInvalid($a);
    }
}
