<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignSendStatusService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Statistics\CampaignSendStatus' shared autowired service.
     *
     * @return \App\Module\Campaigns\Statistics\CampaignSendStatus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/Service/StatisticsProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/StatisticsHandlingTrait.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Statistics/CampaignSendStatus.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Statistics\\CampaignSendStatus'])) {
            return $container->privates['App\\Module\\Campaigns\\Statistics\\CampaignSendStatus'];
        }

        return $container->privates['App\\Module\\Campaigns\\Statistics\\CampaignSendStatus'] = new \App\Module\Campaigns\Statistics\CampaignSendStatus(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->privates['App\\Data\\LegacyHandler\\ListDataQueryHandler'] ?? $container->load('getListDataQueryHandlerService')), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
