<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanUpTemporaryFilesSchedulerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Service\Scheduler\Jobs\CleanUpTemporaryFilesScheduler' shared autowired service.
     *
     * @return \App\Schedulers\Service\Scheduler\Jobs\CleanUpTemporaryFilesScheduler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/SchedulerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/Scheduler/Jobs/CleanUpTemporaryFilesScheduler.php';

        return $container->privates['App\\Schedulers\\Service\\Scheduler\\Jobs\\CleanUpTemporaryFilesScheduler'] = new \App\Schedulers\Service\Scheduler\Jobs\CleanUpTemporaryFilesScheduler(($container->privates['App\\MediaObjects\\Repository\\DefaultMediaObjectManager'] ?? self::getDefaultMediaObjectManagerService($container)), ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')), ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
