<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignResponseByRecipientTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Statistics\CampaignResponseByRecipientType' shared autowired service.
     *
     * @return \App\Module\Campaigns\Statistics\CampaignResponseByRecipientType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/Service/StatisticsProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/StatisticsHandlingTrait.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Statistics/CampaignResponseByRecipientType.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Statistics\\CampaignResponseByRecipientType'])) {
            return $container->privates['App\\Module\\Campaigns\\Statistics\\CampaignResponseByRecipientType'];
        }

        return $container->privates['App\\Module\\Campaigns\\Statistics\\CampaignResponseByRecipientType'] = new \App\Module\Campaigns\Statistics\CampaignResponseByRecipientType(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->privates['App\\Data\\LegacyHandler\\ListDataQueryHandler'] ?? $container->load('getListDataQueryHandlerService')), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a);
    }
}
