<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignsCreateUnsubscribeListService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Record\SaveHandlers\CampaignsCreateUnsubscribeList' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Record\SaveHandlers\CampaignsCreateUnsubscribeList
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordSaveHandlers/BaseModuleSaveHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordSaveHandlers/RecordSaveHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Record/SaveHandlers/CampaignsCreateUnsubscribeList.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailSuppressionListManager'] ?? $container->load('getDefaultEmailSuppressionListManagerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Record\\SaveHandlers\\CampaignsCreateUnsubscribeList'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Record\\SaveHandlers\\CampaignsCreateUnsubscribeList'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Record\\SaveHandlers\\CampaignsCreateUnsubscribeList'] = new \App\Module\Campaigns\Service\Record\SaveHandlers\CampaignsCreateUnsubscribeList($a);
    }
}
