<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultEmailTrackerManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Trackers\DefaultEmailTrackerManager' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Trackers\DefaultEmailTrackerManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Trackers/EmailTrackerManagerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Trackers/DefaultEmailTrackerManager.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'];
        }
        $b = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'] = new \App\Module\Campaigns\Service\Email\Trackers\DefaultEmailTrackerManager(($container->privates['App\\SystemConfig\\LegacyHandler\\LegacySettingsProvider'] ?? $container->load('getLegacySettingsProviderService')), ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')), $a, $b, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
