<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultEmailOptInManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Targets\DefaultEmailOptInManager' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Targets\DefaultEmailOptInManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/EmailOptInManagerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/DefaultEmailOptInManager.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailOptInManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailOptInManager'];
        }
        $b = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'] ?? $container->load('getDefaultEmailTrackerManagerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailOptInManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailOptInManager'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailOptInManager'] = new \App\Module\Campaigns\Service\Email\Targets\DefaultEmailOptInManager(($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')), $a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $b);
    }
}
