<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultEmailQueueProcessorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Queue\DefaultEmailQueueProcessor' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Queue\DefaultEmailQueueProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Queue/EmailQueueProcessorInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Queue/DefaultEmailQueueProcessor.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueManager'] ?? $container->load('getDefaultEmailQueueManagerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueProcessor'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueProcessor'];
        }
        $b = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueProcessor'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueProcessor'];
        }
        $c = ($container->privates['App\\Module\\Campaigns\\Service\\EmailMarketing\\DefaultEmailMarketingManager'] ?? $container->load('getDefaultEmailMarketingManagerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueProcessor'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueProcessor'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueProcessor'] = new \App\Module\Campaigns\Service\Email\Queue\DefaultEmailQueueProcessor($a, ($container->privates['App\\Emails\\LegacyHandler\\EmailProcessProcessor'] ?? $container->load('getEmailProcessProcessorService')), $b, ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Log\\DefaultEmailCampaignLogManager'] ?? $container->load('getDefaultEmailCampaignLogManagerService')), ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\EmailTargetValidatorManager'] ?? $container->load('getEmailTargetValidatorManagerService')), ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')), ($container->privates['App\\SystemConfig\\LegacyHandler\\LegacySettingsProvider'] ?? $container->load('getLegacySettingsProviderService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $c, $a, ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\CampaignEmailParserManager'] ?? $container->load('getCampaignEmailParserManagerService')));
    }
}
