<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultEmailQueueManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Queue\DefaultEmailQueueManager' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Queue\DefaultEmailQueueManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Queue/EmailQueueManagerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Queue/DefaultEmailQueueManager.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueManager'];
        }
        $b = ($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] ?? $container->load('getUserHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueManager'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueManager'] = new \App\Module\Campaigns\Service\Email\Queue\DefaultEmailQueueManager($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $b, ($container->privates['App\\DateTime\\LegacyHandler\\DateTimeHandler'] ?? $container->load('getDateTimeHandlerService')));
    }
}
