<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultEmailCampaignLogManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Log\DefaultEmailCampaignLogManager' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Log\DefaultEmailCampaignLogManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Log/EmailCampaignLogManagerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Log/DefaultEmailCampaignLogManager.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Log\\DefaultEmailCampaignLogManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Log\\DefaultEmailCampaignLogManager'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Log\\DefaultEmailCampaignLogManager'] = new \App\Module\Campaigns\Service\Email\Log\DefaultEmailCampaignLogManager($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->privates['App\\DateTime\\LegacyHandler\\DateTimeHandler'] ?? $container->load('getDateTimeHandlerService')));
    }
}
