<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteTestMailMarketingEntriesActionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\Service\RecordActions\DeleteTestMailMarketingEntriesAction' shared autowired service.
     *
     * @return \App\Process\Service\RecordActions\DeleteTestMailMarketingEntriesAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/RecordActions/DeleteTestMailMarketingEntriesAction.php';

        $a = ($container->privates['App\\Module\\EmailMarketing\\Service\\Actions\\DeleteTestMailMarketingEntriesService'] ?? $container->load('getDeleteTestMailMarketingEntriesServiceService'));

        if (isset($container->privates['App\\Process\\Service\\RecordActions\\DeleteTestMailMarketingEntriesAction'])) {
            return $container->privates['App\\Process\\Service\\RecordActions\\DeleteTestMailMarketingEntriesAction'];
        }
        $b = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Process\\Service\\RecordActions\\DeleteTestMailMarketingEntriesAction'])) {
            return $container->privates['App\\Process\\Service\\RecordActions\\DeleteTestMailMarketingEntriesAction'];
        }

        return $container->privates['App\\Process\\Service\\RecordActions\\DeleteTestMailMarketingEntriesAction'] = new \App\Process\Service\RecordActions\DeleteTestMailMarketingEntriesAction(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, $b, ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)));
    }
}
