<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultEmailMarketingManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\EmailMarketing\DefaultEmailMarketingManager' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\EmailMarketing\DefaultEmailMarketingManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/EmailMarketing/EmailMarketingManagerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/EmailMarketing/DefaultEmailMarketingManager.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\EmailMarketing\\DefaultEmailMarketingManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\EmailMarketing\\DefaultEmailMarketingManager'];
        }
        $b = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\EmailMarketing\\DefaultEmailMarketingManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\EmailMarketing\\DefaultEmailMarketingManager'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\EmailMarketing\\DefaultEmailMarketingManager'] = new \App\Module\Campaigns\Service\EmailMarketing\DefaultEmailMarketingManager($a, $b, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
