<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteRecordThreadItemActionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\Service\RecordThreadItemActions\DeleteRecordThreadItemAction' shared autowired service.
     *
     * @return \App\Process\Service\RecordThreadItemActions\DeleteRecordThreadItemAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/RecordThreadItemActions/DeleteRecordThreadItemAction.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordDeletionHandler'] ?? $container->load('getRecordDeletionHandlerService'));

        if (isset($container->privates['App\\Process\\Service\\RecordThreadItemActions\\DeleteRecordThreadItemAction'])) {
            return $container->privates['App\\Process\\Service\\RecordThreadItemActions\\DeleteRecordThreadItemAction'];
        }

        return $container->privates['App\\Process\\Service\\RecordThreadItemActions\\DeleteRecordThreadItemAction'] = new \App\Process\Service\RecordThreadItemActions\DeleteRecordThreadItemAction(($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), $a);
    }
}
