<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultEmailSuppressionListManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Targets\DefaultEmailSuppressionListManager' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Targets\DefaultEmailSuppressionListManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/EmailSuppressionListManagerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/DefaultEmailSuppressionListManager.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailSuppressionListManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailSuppressionListManager'];
        }
        $b = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailSuppressionListManager'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailSuppressionListManager'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailSuppressionListManager'] = new \App\Module\Campaigns\Service\Email\Targets\DefaultEmailSuppressionListManager($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $b);
    }
}
