<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTargetValidatorManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Targets\EmailTargetValidatorManager' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Targets\EmailTargetValidatorManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/EmailTargetValidatorManager.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/EmailTargetValidatorRegistry.php';

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\EmailTargetValidatorManager'] = new \App\Module\Campaigns\Service\Email\Targets\EmailTargetValidatorManager(new \App\Module\Campaigns\Service\Email\Targets\Validation\EmailTargetValidatorRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckDomainSuppressionList'] ?? $container->load('getCheckDomainSuppressionListService'));
            yield 1 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckDuplicateEmail'] ?? $container->load('getCheckDuplicateEmailService'));
            yield 2 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckEmailAddressSuppressionList'] ?? $container->load('getCheckEmailAddressSuppressionListService'));
            yield 3 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckEmailMarkedInvalid'] ?? $container->load('getCheckEmailMarkedInvalidService'));
            yield 4 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\CheckIdSuppressionList'] ?? $container->load('getCheckIdSuppressionListService'));
            yield 5 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\HasPrimaryEmailAddress'] ?? $container->load('getHasPrimaryEmailAddressService'));
            yield 6 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Default\\IsValidEmailAddress'] ?? $container->load('getIsValidEmailAddressService'));
            yield 7 => ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Marketing\\IsOptedIn'] ?? $container->load('getIsOptedInService'));
        }, 8)));
    }
}
