<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailMarketingStatusActionCheckerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\Checkers\EmailMarketingStatusActionChecker' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\Checkers\EmailMarketingStatusActionChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Service/ActionAvailabilityChecker/ActionAvailabilityCheckerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/EmailMarketing/Checkers/EmailMarketingStatusActionChecker.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\Checkers\\EmailMarketingStatusActionChecker'])) {
            return $container->privates['App\\Module\\EmailMarketing\\Checkers\\EmailMarketingStatusActionChecker'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\Checkers\\EmailMarketingStatusActionChecker'] = new \App\Module\EmailMarketing\Checkers\EmailMarketingStatusActionChecker($a);
    }
}
