<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntryPointControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\EntryPoint\Controller\EntryPointController' shared autowired service.
     *
     * @return \App\EntryPoint\Controller\EntryPointController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 3).'/core/backend/EntryPoint/Controller/EntryPointController.php';

        $container->services['App\\EntryPoint\\Controller\\EntryPointController'] = $instance = new \App\EntryPoint\Controller\EntryPointController();

        $instance->setContainer(($container->privates['.service_locator.yIXVn50'] ?? $container->load('get_ServiceLocator_YIXVn50Service'))->withContext('App\\EntryPoint\\Controller\\EntryPointController', $container));

        return $instance;
    }
}
