<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailProcessProcessorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Emails\LegacyHandler\EmailProcessProcessor' shared autowired service.
     *
     * @return \App\Emails\LegacyHandler\EmailProcessProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/LegacyHandler/EmailProcessProcessor.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/Service/EmailParserHandler/EmailParserManager.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/Service/EmailParserHandler/EmailParserMapperTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/Service/EmailParserHandler/EmailParserRegistry.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Emails\\LegacyHandler\\EmailProcessProcessor'])) {
            return $container->privates['App\\Emails\\LegacyHandler\\EmailProcessProcessor'];
        }
        $b = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Emails\\LegacyHandler\\EmailProcessProcessor'])) {
            return $container->privates['App\\Emails\\LegacyHandler\\EmailProcessProcessor'];
        }

        return $container->privates['App\\Emails\\LegacyHandler\\EmailProcessProcessor'] = new \App\Emails\LegacyHandler\EmailProcessProcessor(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Emails\\LegacyHandler\\SendEmailHandler'] ?? $container->load('getSendEmailHandlerService')), $a, $b, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), new \App\Emails\Service\EmailParserHandler\EmailParserManager(new \App\Emails\Service\EmailParserHandler\EmailParserRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Emails\\LegacyHandler\\Parsers\\LegacyEmailParser'] ?? $container->load('getLegacyEmailParserService'));
        }, 1))));
    }
}
