<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldDefinitionStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\FieldDefinitions\DataProvider\FieldDefinitionStateProvider' shared autowired service.
     *
     * @return \App\FieldDefinitions\DataProvider\FieldDefinitionStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/DataProvider/FieldDefinitionStateProvider.php';

        $a = ($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService'));

        if (isset($container->privates['App\\FieldDefinitions\\DataProvider\\FieldDefinitionStateProvider'])) {
            return $container->privates['App\\FieldDefinitions\\DataProvider\\FieldDefinitionStateProvider'];
        }

        return $container->privates['App\\FieldDefinitions\\DataProvider\\FieldDefinitionStateProvider'] = new \App\FieldDefinitions\DataProvider\FieldDefinitionStateProvider($a);
    }
}
