<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterEmailListHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Emails\LegacyHandler\FilterEmailListHandler' shared autowired service.
     *
     * @return \App\Emails\LegacyHandler\FilterEmailListHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/LegacyHandler/FilterEmailListHandler.php';

        return $container->privates['App\\Emails\\LegacyHandler\\FilterEmailListHandler'] = new \App\Emails\LegacyHandler\FilterEmailListHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
