<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileFieldSoftDeleteHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Service\Fields\File\DeleteHandlers\FileFieldSoftDeleteHandler' shared autowired service.
     *
     * @return \App\Module\Service\Fields\File\DeleteHandlers\FileFieldSoftDeleteHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['App\\Module\\Service\\Fields\\File\\DeleteHandlers\\FileFieldSoftDeleteHandler'] = $container->createProxy('FileFieldSoftDeleteHandlerGhost0f62add', static fn () => \FileFieldSoftDeleteHandlerGhost0f62add::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordDeleteHandlers/BaseModuleDeleteHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordDeleteHandlers/RecordFieldTypeDeleteHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Module/Service/Fields/File/DeleteHandlers/FileFieldSoftDeleteHandler.php';

        return ($lazyLoad->__construct(($container->privates['App\\MediaObjects\\Repository\\DefaultMediaObjectManager'] ?? self::getDefaultMediaObjectManagerService($container)), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container))) && false ?: $lazyLoad);
    }
}
