<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoryTimelineDataHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\LegacyHandler\PresetDataHandlers\HistoryTimelineDataHandler' shared autowired service.
     *
     * @return \App\Data\LegacyHandler\PresetDataHandlers\HistoryTimelineDataHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/PresetDataHandlers/SubpanelDataQueryHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/ListDataHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/PresetListDataHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/StatisticsHandlingTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/PresetDataHandlers/HistoryTimelineDataHandler.php';

        $a = ($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService'));

        if (isset($container->privates['App\\Data\\LegacyHandler\\PresetDataHandlers\\HistoryTimelineDataHandler'])) {
            return $container->privates['App\\Data\\LegacyHandler\\PresetDataHandlers\\HistoryTimelineDataHandler'];
        }
        $b = ($container->privates['App\\Languages\\Service\\LanguageManager'] ?? $container->load('getLanguageManagerService'));

        if (isset($container->privates['App\\Data\\LegacyHandler\\PresetDataHandlers\\HistoryTimelineDataHandler'])) {
            return $container->privates['App\\Data\\LegacyHandler\\PresetDataHandlers\\HistoryTimelineDataHandler'];
        }

        $container->privates['App\\Data\\LegacyHandler\\PresetDataHandlers\\HistoryTimelineDataHandler'] = $instance = new \App\Data\LegacyHandler\PresetDataHandlers\HistoryTimelineDataHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Data\\LegacyHandler\\RecordMapper'] ?? $container->load('getRecordMapperService')), $a, $b);

        $instance->setLogger(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        return $instance;
    }
}
