<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIsOptedInService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Marketing\IsOptedIn' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Marketing\IsOptedIn
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/EmailTargetValidatorInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/BaseEmailTargetValidator.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Targets/Validation/Validators/Marketing/IsOptedIn.php';

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\Validation\\Validators\\Marketing\\IsOptedIn'] = new \App\Module\Campaigns\Service\Email\Targets\Validation\Validators\Marketing\IsOptedIn(($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailOptInManager'] ?? $container->load('getDefaultEmailOptInManagerService')));
    }
}
