<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitTrackersEnabledDefaultService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\Service\Fields\InitTrackersEnabledDefault' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\Service\Fields\InitTrackersEnabledDefault
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/EmailMarketing/Service/Fields/InitTrackersEnabledDefault.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'] ?? $container->load('getDefaultEmailTrackerManagerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitTrackersEnabledDefault'])) {
            return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitTrackersEnabledDefault'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitTrackersEnabledDefault'] = new \App\Module\EmailMarketing\Service\Fields\InitTrackersEnabledDefault($a);
    }
}
