<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitOutboundEmailDefaultService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\Service\Fields\InitOutboundEmailDefault' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\Service\Fields\InitOutboundEmailDefault
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/EmailMarketing/Service/Fields/InitOutboundEmailDefault.php';

        $a = ($container->privates['App\\UserPreferences\\LegacyHandler\\UserPreferenceHandler'] ?? $container->load('getUserPreferenceHandlerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitOutboundEmailDefault'])) {
            return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitOutboundEmailDefault'];
        }
        $b = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitOutboundEmailDefault'])) {
            return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitOutboundEmailDefault'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitOutboundEmailDefault'] = new \App\Module\EmailMarketing\Service\Fields\InitOutboundEmailDefault($a, $b);
    }
}
