<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInsertEmailTemplateActionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Emails\Service\RecordActions\InsertEmailTemplateAction' shared autowired service.
     *
     * @return \App\Module\Emails\Service\RecordActions\InsertEmailTemplateAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Emails/Service/RecordActions/InsertEmailTemplateAction.php';

        return $container->privates['App\\Module\\Emails\\Service\\RecordActions\\InsertEmailTemplateAction'] = new \App\Module\Emails\Service\RecordActions\InsertEmailTemplateAction(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)));
    }
}
