<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobIntervalListApiMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Service\Fields\JobIntervalListApiMapper' shared autowired service.
     *
     * @return \App\Schedulers\Service\Fields\JobIntervalListApiMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['App\\Schedulers\\Service\\Fields\\JobIntervalListApiMapper'] = $container->createProxy('JobIntervalListApiMapperGhostBc29761', static fn () => \JobIntervalListApiMapperGhostBc29761::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseModuleMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseFieldMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/ApiRecordMappers/ApiRecordFieldMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/Fields/JobIntervalListApiMapper.php';

        return ($lazyLoad->__construct(($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), ($container->services['app.cron.handler'] ?? $container->load('getApp_Cron_HandlerService'))) && false ?: $lazyLoad);
    }
}
