<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyEmailParserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Emails\LegacyHandler\Parsers\LegacyEmailParser' shared autowired service.
     *
     * @return \App\Emails\LegacyHandler\Parsers\LegacyEmailParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/Service/EmailParserHandler/EmailParserInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/LegacyHandler/Parsers/LegacyEmailParser.php';

        return $container->privates['App\\Emails\\LegacyHandler\\Parsers\\LegacyEmailParser'] = new \App\Emails\LegacyHandler\Parsers\LegacyEmailParser(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')), ($container->privates['App\\DateTime\\LegacyHandler\\DateTimeHandler'] ?? $container->load('getDateTimeHandlerService')));
    }
}
