<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaxFileSizeUploadValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\MediaObjects\Validator\UploadValidator\Validators\MaxFileSizeUploadValidator' shared autowired service.
     *
     * @return \App\MediaObjects\Validator\UploadValidator\Validators\MaxFileSizeUploadValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Validator/UploadValidator/UploadValidatorInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Validator/UploadValidator/Validators/MaxFileSizeUploadValidator.php';

        $a = ($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService'));

        if (isset($container->privates['App\\MediaObjects\\Validator\\UploadValidator\\Validators\\MaxFileSizeUploadValidator'])) {
            return $container->privates['App\\MediaObjects\\Validator\\UploadValidator\\Validators\\MaxFileSizeUploadValidator'];
        }

        return $container->privates['App\\MediaObjects\\Validator\\UploadValidator\\Validators\\MaxFileSizeUploadValidator'] = new \App\MediaObjects\Validator\UploadValidator\Validators\MaxFileSizeUploadValidator(($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')), $a);
    }
}
