<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\MediaObjects\Controller\MediaController' shared autowired service.
     *
     * @return \App\MediaObjects\Controller\MediaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Controller/MediaController.php';

        $container->services['App\\MediaObjects\\Controller\\MediaController'] = $instance = new \App\MediaObjects\Controller\MediaController(($container->privates['App\\MediaObjects\\Repository\\ArchivedDocumentMediaObjectRepository'] ?? self::getArchivedDocumentMediaObjectRepositoryService($container)), ($container->privates['App\\MediaObjects\\Repository\\PrivateDocumentMediaObjectRepository'] ?? self::getPrivateDocumentMediaObjectRepositoryService($container)), ($container->privates['App\\MediaObjects\\Repository\\PrivateImageMediaObjectRepository'] ?? self::getPrivateImageMediaObjectRepositoryService($container)), ($container->privates['App\\Engine\\LegacyHandler\\AclHandler'] ?? $container->load('getAclHandlerService')));

        $instance->setContainer(($container->privates['.service_locator.yIXVn50'] ?? $container->load('get_ServiceLocator_YIXVn50Service'))->withContext('App\\MediaObjects\\Controller\\MediaController', $container));

        return $instance;
    }
}
