<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessProcessorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\DataPersister\ProcessProcessor' shared autowired service.
     *
     * @return \App\Process\DataPersister\ProcessProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/DataPersister/ProcessProcessor.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerRegistry.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Process\\DataPersister\\ProcessProcessor'])) {
            return $container->privates['App\\Process\\DataPersister\\ProcessProcessor'];
        }

        return $container->privates['App\\Process\\DataPersister\\ProcessProcessor'] = new \App\Process\DataPersister\ProcessProcessor(new \App\Process\Service\ProcessHandlerRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Install\\Service\\Installation\\InstallActionHandler'] ?? $container->load('getInstallActionHandlerService'));
            yield 1 => ($container->privates['App\\Languages\\LegacyHandler\\SetSessionLanguage'] ?? $container->load('getSetSessionLanguageService'));
            yield 2 => ($container->privates['App\\Module\\LegacyHandler\\Favorites\\UpdateFavorite'] ?? $container->load('getUpdateFavoriteService'));
            yield 3 => ($container->privates['App\\Module\\LegacyHandler\\RecentlyViewed\\AddRecentlyViewed'] ?? $container->load('getAddRecentlyViewedService'));
            yield 4 => ($container->privates['App\\Process\\LegacyHandler\\ACL\\UserACLHandler'] ?? $container->load('getUserACLHandlerService'));
            yield 5 => ($container->privates['App\\Process\\LegacyHandler\\AddContactsToTargetListBulkActionHandler'] ?? $container->load('getAddContactsToTargetListBulkActionHandlerService'));
            yield 6 => ($container->privates['App\\Process\\LegacyHandler\\AddRecordsToTargetListBulkActionHandler'] ?? $container->load('getAddRecordsToTargetListBulkActionHandlerService'));
            yield 7 => ($container->privates['App\\Process\\LegacyHandler\\CheckTwoFactorCodeHandler'] ?? $container->load('getCheckTwoFactorCodeHandlerService'));
            yield 8 => ($container->privates['App\\Process\\LegacyHandler\\CreatePortalUserActionHandler'] ?? $container->load('getCreatePortalUserActionHandlerService'));
            yield 9 => ($container->privates['App\\Process\\LegacyHandler\\DisablePortalUserActionHandler'] ?? $container->load('getDisablePortalUserActionHandlerService'));
            yield 10 => ($container->privates['App\\Process\\LegacyHandler\\EnablePortalUserActionHandler'] ?? $container->load('getEnablePortalUserActionHandlerService'));
            yield 11 => ($container->privates['App\\Process\\LegacyHandler\\GenerateBackupCodesHandler'] ?? $container->load('getGenerateBackupCodesHandlerService'));
            yield 12 => ($container->privates['App\\Process\\LegacyHandler\\LinkRelationHandler'] ?? $container->load('getLinkRelationHandlerService'));
            yield 13 => ($container->privates['App\\Process\\LegacyHandler\\ResetPasswordHandler'] ?? $container->load('getResetPasswordHandlerService'));
            yield 14 => ($container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'] ?? $container->load('getSendTestEmailHandlerService'));
            yield 15 => ($container->privates['App\\Process\\LegacyHandler\\SendTestEmailValidation'] ?? $container->load('getSendTestEmailValidationService'));
            yield 16 => ($container->privates['App\\Process\\LegacyHandler\\UnlinkRelationHandler'] ?? $container->load('getUnlinkRelationHandlerService'));
            yield 17 => ($container->privates['App\\Process\\Service\\BulkActions\\CsvExportBulkAction'] ?? $container->load('getCsvExportBulkActionService'));
            yield 18 => ($container->privates['App\\Process\\Service\\BulkActions\\DeleteRecordsBulkAction'] ?? $container->load('getDeleteRecordsBulkActionService'));
            yield 19 => ($container->privates['App\\Process\\Service\\BulkActions\\MassUpdateBulkAction'] ?? $container->load('getMassUpdateBulkActionService'));
            yield 20 => ($container->privates['App\\Process\\Service\\BulkActions\\MergeRecordsBulkAction'] ?? $container->load('getMergeRecordsBulkActionService'));
            yield 21 => ($container->privates['App\\Process\\Service\\BulkActions\\PrintAsPdfBulkAction'] ?? $container->load('getPrintAsPdfBulkActionService'));
            yield 22 => ($container->privates['App\\Process\\Service\\FieldDefault\\DateFieldDefaultCalculation'] ?? $container->load('getDateFieldDefaultCalculationService'));
            yield 23 => ($container->privates['App\\Process\\Service\\NavbarActions\\OpenRecordModalAction'] ??= new \App\Process\Service\NavbarActions\OpenRecordModalAction());
            yield 24 => ($container->privates['App\\Process\\Service\\RecordActions\\AbortEmailMarketing'] ?? $container->load('getAbortEmailMarketingService'));
            yield 25 => ($container->privates['App\\Process\\Service\\RecordActions\\ChangeLogAction'] ?? $container->load('getChangeLogActionService'));
            yield 26 => ($container->privates['App\\Process\\Service\\RecordActions\\ConvertLeadAction'] ?? $container->load('getConvertLeadActionService'));
            yield 27 => ($container->privates['App\\Process\\Service\\RecordActions\\ConvertRecordAction'] ?? $container->load('getConvertRecordActionService'));
            yield 28 => ($container->privates['App\\Process\\Service\\RecordActions\\DeleteRecordAction'] ?? $container->load('getDeleteRecordActionService'));
            yield 29 => ($container->privates['App\\Process\\Service\\RecordActions\\DeleteTestMailMarketingEntriesAction'] ?? $container->load('getDeleteTestMailMarketingEntriesActionService'));
            yield 30 => ($container->privates['App\\Process\\Service\\RecordActions\\DuplicateRecordAction'] ?? $container->load('getDuplicateRecordActionService'));
            yield 31 => ($container->privates['App\\Process\\Service\\RecordActions\\EditAction'] ?? $container->load('getEditActionService'));
            yield 32 => ($container->privates['App\\Process\\Service\\RecordActions\\MergeDuplicateAction'] ?? $container->load('getMergeDuplicateActionService'));
            yield 33 => ($container->privates['App\\Process\\Service\\RecordActions\\PrintAsPdfAction'] ?? $container->load('getPrintAsPdfActionService'));
            yield 34 => ($container->privates['App\\Process\\Service\\RecordActions\\ScheduleEmailMarketingAction'] ?? $container->load('getScheduleEmailMarketingActionService'));
            yield 35 => ($container->privates['App\\Process\\Service\\RecordActions\\SendEmailAction'] ?? $container->load('getSendEmailActionService'));
            yield 36 => ($container->privates['App\\Process\\Service\\RecordActions\\UnscheduleEmailMarketingAction'] ?? $container->load('getUnscheduleEmailMarketingActionService'));
            yield 37 => ($container->privates['App\\Process\\Service\\RecordThreadItemActions\\DeleteRecordThreadItemAction'] ?? $container->load('getDeleteRecordThreadItemActionService'));
            yield 38 => ($container->privates['App\\Process\\Service\\RecordThreadItemActions\\DismissAlertAction'] ?? $container->load('getDismissAlertActionService'));
            yield 39 => ($container->privates['App\\Process\\Service\\RecordThreadItemActions\\SnoozeRecordThreadItemAction'] ?? $container->load('getSnoozeRecordThreadItemActionService'));
            yield 40 => ($container->privates['App\\Process\\Service\\RecordThreadListActions\\DeleteAllRecordThreadListAction'] ?? $container->load('getDeleteAllRecordThreadListActionService'));
            yield 41 => ($container->privates['App\\Process\\Service\\RecordThreadListActions\\DismissAllAlertsRecordThreadListAction'] ?? $container->load('getDismissAllAlertsRecordThreadListActionService'));
            yield 42 => ($container->privates['App\\Process\\Service\\RecordThreadListActions\\MarkAsReadRecordThreadListAction'] ?? $container->load('getMarkAsReadRecordThreadListActionService'));
            yield 43 => ($container->privates['App\\Process\\Service\\TableActions\\SendBatchedCampaignEmails'] ?? $container->load('getSendBatchedCampaignEmailsService'));
            yield 44 => ($container->privates['App\\UserPreferences\\LegacyHandler\\SaveUiPreferences'] ?? $container->load('getSaveUiPreferencesService'));
            yield 45 => ($container->privates['App\\UserPreferences\\LegacyHandler\\SetUserLanguage'] ?? $container->load('getSetUserLanguageService'));
            yield 46 => ($container->privates['App\\Module\\EmailMarketing\\LegacyHandler\\Validation\\Validators\\UnsubscribeValidator'] ?? $container->load('getUnsubscribeValidatorService'));
            yield 47 => ($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitCurrencyDefault'] ?? $container->load('getInitCurrencyDefaultService'));
            yield 48 => ($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitOutboundEmailDefault'] ?? $container->load('getInitOutboundEmailDefaultService'));
            yield 49 => ($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\InitTrackersEnabledDefault'] ?? $container->load('getInitTrackersEnabledDefaultService'));
            yield 50 => ($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\UpdateEmailTemplateBody'] ?? $container->load('getUpdateEmailTemplateBodyService'));
            yield 51 => ($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\UpdateEmailTemplateSubject'] ?? $container->load('getUpdateEmailTemplateSubjectService'));
            yield 52 => ($container->privates['App\\Module\\Emails\\Service\\RecordActions\\InsertEmailTemplateAction'] ?? $container->load('getInsertEmailTemplateActionService'));
        }, 53)), $a, ($container->privates['App\\Engine\\LegacyHandler\\AclHandler'] ?? $container->load('getAclHandlerService')));
    }
}
