<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPruneDatabaseSchedulerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Service\Scheduler\Jobs\PruneDatabaseScheduler' shared autowired service.
     *
     * @return \App\Schedulers\Service\Scheduler\Jobs\PruneDatabaseScheduler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/SchedulerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/Scheduler/Jobs/PruneDatabaseScheduler.php';

        return $container->privates['App\\Schedulers\\Service\\Scheduler\\Jobs\\PruneDatabaseScheduler'] = new \App\Schedulers\Service\Scheduler\Jobs\PruneDatabaseScheduler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Data\\Service\\Record\\RecordDeleteHandlers\\RecordDeleteHandlerRunner'] ?? $container->load('getRecordDeleteHandlerRunnerService')), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)));
    }
}
