<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParentTypeDefaultMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\FieldDefinitions\LegacyHandler\DefaultMapper\ParentTypeDefaultMapper' shared autowired service.
     *
     * @return \App\FieldDefinitions\LegacyHandler\DefaultMapper\ParentTypeDefaultMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/Service/VardefConfigMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/LegacyHandler/DefaultMapper/ParentTypeDefaultMapper.php';

        $a = ($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] ?? $container->load('getUserHandlerService'));

        if (isset($container->privates['App\\FieldDefinitions\\LegacyHandler\\DefaultMapper\\ParentTypeDefaultMapper'])) {
            return $container->privates['App\\FieldDefinitions\\LegacyHandler\\DefaultMapper\\ParentTypeDefaultMapper'];
        }

        return $container->privates['App\\FieldDefinitions\\LegacyHandler\\DefaultMapper\\ParentTypeDefaultMapper'] = new \App\FieldDefinitions\LegacyHandler\DefaultMapper\ParentTypeDefaultMapper(($container->privates['App\\Languages\\LegacyHandler\\AppListStringsHandler'] ?? $container->load('getAppListStringsHandlerService')), $a);
    }
}
