<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordSaveHandlerRegistryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\Service\Record\RecordSaveHandlers\RecordSaveHandlerRegistry' shared autowired service.
     *
     * @return \App\Data\Service\Record\RecordSaveHandlers\RecordSaveHandlerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['App\\Data\\Service\\Record\\RecordSaveHandlers\\RecordSaveHandlerRegistry'] = $container->createProxy('RecordSaveHandlerRegistryGhostF9c3335', static fn () => \RecordSaveHandlerRegistryGhostF9c3335::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordSaveHandlers/ModuleSaveHandlerTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordSaveHandlers/RecordSaveHandlerTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordSaveHandlers/RecordSaveHandlerRegistry.php';

        return ($lazyLoad->__construct(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Module\\Campaigns\\Service\\Record\\SaveHandlers\\CampaignsCreateUnsubscribeList'] ?? $container->load('getCampaignsCreateUnsubscribeListService'));
        }, 1)) && false ?: $lazyLoad);
    }
}
