<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordTableWidgetDefinitionParserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\ViewDefinitions\LegacyHandler\Widgets\DefinitionParsers\RecordTableWidgetDefinitionParser' shared autowired service.
     *
     * @return \App\ViewDefinitions\LegacyHandler\Widgets\DefinitionParsers\RecordTableWidgetDefinitionParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/LegacyHandler/Widgets/WidgetDefinitionParserInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Service/DefinitionEntryHandlingTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/ViewDefinitions/LegacyHandler/Widgets/DefinitionParsers/RecordTableWidgetDefinitionParser.php';

        return $container->privates['App\\ViewDefinitions\\LegacyHandler\\Widgets\\DefinitionParsers\\RecordTableWidgetDefinitionParser'] = new \App\ViewDefinitions\LegacyHandler\Widgets\DefinitionParsers\RecordTableWidgetDefinitionParser(($container->privates['App\\Engine\\Service\\ActionAvailabilityChecker\\ActionAvailabilityChecker'] ?? $container->load('getActionAvailabilityCheckerService')));
    }
}
