<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordDeleteHandlerRunnerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\Service\Record\RecordDeleteHandlers\RecordDeleteHandlerRunner' shared autowired service.
     *
     * @return \App\Data\Service\Record\RecordDeleteHandlers\RecordDeleteHandlerRunner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordDeleteHandlers/RecordDeleteHandlerRunnerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordDeleteHandlers/RecordDeleteHandlerRunner.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordDeleteHandlers/ModuleDeleteHandlerTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordDeleteHandlers/RecordFieldDeleteHandlerTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordDeleteHandlers/RecordFieldDeleteHandlerRegistry.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/RecordDeleteHandlers/RecordFieldTypeDeleteHandlerRegistry.php';

        $a = ($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService'));

        if (isset($container->privates['App\\Data\\Service\\Record\\RecordDeleteHandlers\\RecordDeleteHandlerRunner'])) {
            return $container->privates['App\\Data\\Service\\Record\\RecordDeleteHandlers\\RecordDeleteHandlerRunner'];
        }

        return $container->privates['App\\Data\\Service\\Record\\RecordDeleteHandlers\\RecordDeleteHandlerRunner'] = new \App\Data\Service\Record\RecordDeleteHandlers\RecordDeleteHandlerRunner(new \App\Data\Service\Record\RecordDeleteHandlers\RecordFieldDeleteHandlerRegistry(new RewindableGenerator(fn () => new \EmptyIterator(), 0)), new \App\Data\Service\Record\RecordDeleteHandlers\RecordFieldTypeDeleteHandlerRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Module\\Service\\Fields\\Attachments\\DeleteHandlers\\AttachmentsFieldHardDeleteHandler'] ?? $container->load('getAttachmentsFieldHardDeleteHandlerService'));
            yield 1 => ($container->privates['App\\Module\\Service\\Fields\\Attachments\\DeleteHandlers\\AttachmentsFieldSoftDeleteHandler'] ?? $container->load('getAttachmentsFieldSoftDeleteHandlerService'));
            yield 2 => ($container->privates['App\\Module\\Service\\Fields\\File\\DeleteHandlers\\FileFieldHardDeleteHandler'] ?? $container->load('getFileFieldHardDeleteHandlerService'));
            yield 3 => ($container->privates['App\\Module\\Service\\Fields\\File\\DeleteHandlers\\FileFieldSoftDeleteHandler'] ?? $container->load('getFileFieldSoftDeleteHandlerService'));
        }, 4)), ($container->privates['App\\Data\\Service\\Record\\RecordDeleteHandlers\\RecordDeleteHandlerRegistry'] ?? $container->load('getRecordDeleteHandlerRegistryService')), $a);
    }
}
