<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRangeListApiMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Service\Fields\RangeListApiMapper' shared autowired service.
     *
     * @return \App\Schedulers\Service\Fields\RangeListApiMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseModuleMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseFieldMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/ApiRecordMappers/ApiRecordFieldMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/Fields/RangeListApiMapper.php';

        $a = ($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] ?? $container->load('getUserHandlerService'));

        if (isset($container->privates['App\\Schedulers\\Service\\Fields\\RangeListApiMapper'])) {
            return $container->privates['App\\Schedulers\\Service\\Fields\\RangeListApiMapper'];
        }

        return $container->privates['App\\Schedulers\\Service\\Fields\\RangeListApiMapper'] = new \App\Schedulers\Service\Fields\RangeListApiMapper($a, ($container->privates['App\\Languages\\LegacyHandler\\ModStringsHandler'] ?? $container->load('getModStringsHandlerService')), ($container->privates['App\\DateTime\\LegacyHandler\\DateTimeHandler'] ?? $container->load('getDateTimeHandlerService')));
    }
}
