<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordDeletionHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\LegacyHandler\RecordDeletionHandler' shared autowired service.
     *
     * @return \App\Data\LegacyHandler\RecordDeletionHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/RecordDeletionServiceInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/LegacyHandler/RecordDeletionHandler.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordListHandler'] ?? $container->load('getRecordListHandlerService'));

        if (isset($container->privates['App\\Data\\LegacyHandler\\RecordDeletionHandler'])) {
            return $container->privates['App\\Data\\LegacyHandler\\RecordDeletionHandler'];
        }
        $b = ($container->privates['App\\Data\\Service\\Record\\RecordDeleteHandlers\\RecordDeleteHandlerRunner'] ?? $container->load('getRecordDeleteHandlerRunnerService'));

        if (isset($container->privates['App\\Data\\LegacyHandler\\RecordDeletionHandler'])) {
            return $container->privates['App\\Data\\LegacyHandler\\RecordDeletionHandler'];
        }

        return $container->privates['App\\Data\\LegacyHandler\\RecordDeletionHandler'] = new \App\Data\LegacyHandler\RecordDeletionHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), $a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $b);
    }
}
