<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunSchedulersCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Command\RunSchedulersCommand' shared autowired service.
     *
     * @return \App\Schedulers\Command\RunSchedulersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Command/BaseCommand.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Command/RunSchedulersCommand.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/LegacyHandler/SchedulerHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/SchedulerRegistry.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Runners/LegacySchedulerRunner.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Runners/SchedulerRunner.php';

        $a = ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState());
        $b = ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack());
        $c = new \App\Schedulers\Service\SchedulerRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Schedulers\\Service\\Scheduler\\Jobs\\AddEmailToQueueScheduler'] ?? $container->load('getAddEmailToQueueSchedulerService'));
            yield 1 => ($container->privates['App\\Schedulers\\Service\\Scheduler\\Jobs\\CleanUpTemporaryFilesScheduler'] ?? $container->load('getCleanUpTemporaryFilesSchedulerService'));
            yield 2 => ($container->privates['App\\Schedulers\\Service\\Scheduler\\Jobs\\PruneDatabaseScheduler'] ?? $container->load('getPruneDatabaseSchedulerService'));
            yield 3 => ($container->privates['App\\Schedulers\\Service\\Scheduler\\Jobs\\SendEmailScheduler'] ?? $container->load('getSendEmailSchedulerService'));
        }, 4));
        $d = ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService'));
        $e = ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container));

        $container->privates['App\\Schedulers\\Command\\RunSchedulersCommand'] = $instance = new \App\Schedulers\Command\RunSchedulersCommand(new \App\Schedulers\LegacyHandler\SchedulerHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', $a, $b, $c, $d, ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService')), new \App\Schedulers\Runners\LegacySchedulerRunner(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', $a, $b, $e), new \App\Schedulers\Runners\SchedulerRunner($c, $e), $e), ($container->privates['App\\Authentication\\LegacyHandler\\Authentication'] ?? $container->load('getAuthenticationService')), ($container->privates['App\\Engine\\LegacyHandler\\DefaultLegacyHandler'] ?? $container->load('getDefaultLegacyHandlerService')), $d);

        $instance->setDefaultSessionName('SCRMSESSID');
        $instance->setLegacySessionName('SCRMSESSID');
        $instance->setRequestStack($b);
        $instance->setAppStringsHandler(($container->privates['App\\Languages\\LegacyHandler\\AppStringsHandler'] ?? $container->load('getAppStringsHandlerService')));
        $instance->setCronHandler(($container->services['app.cron.handler'] ?? $container->load('getApp_Cron_HandlerService')));
        $instance->setLastRunTracker(($container->privates['App\\Install\\Service\\CommandLastRunTracker'] ?? $container->load('getCommandLastRunTrackerService')));
        $instance->setName('schedulers:run');

        return $instance;
    }
}
