<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordListStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\DataProvider\RecordListStateProvider' shared autowired service.
     *
     * @return \App\Data\DataProvider\RecordListStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/DataProvider/RecordListStateProvider.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\RecordListHandler'] ?? $container->load('getRecordListHandlerService'));

        if (isset($container->privates['App\\Data\\DataProvider\\RecordListStateProvider'])) {
            return $container->privates['App\\Data\\DataProvider\\RecordListStateProvider'];
        }
        $b = ($container->privates['App\\Data\\Service\\Record\\ApiRecordMappers\\ApiRecordMapperRunner'] ?? $container->load('getApiRecordMapperRunnerService'));

        if (isset($container->privates['App\\Data\\DataProvider\\RecordListStateProvider'])) {
            return $container->privates['App\\Data\\DataProvider\\RecordListStateProvider'];
        }

        return $container->privates['App\\Data\\DataProvider\\RecordListStateProvider'] = new \App\Data\DataProvider\RecordListStateProvider($a, $b);
    }
}
