<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordInitDoctrineEventListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\EventSubscriber\RecordInitDoctrineEventListener' shared autowired service.
     *
     * @return \App\Data\EventSubscriber\RecordInitDoctrineEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/EventSubscriber/RecordInitDoctrineEventListener.php';

        $a = ($container->privates['App\\Authentication\\LegacyHandler\\UserHandler'] ?? $container->load('getUserHandlerService'));

        if (isset($container->privates['App\\Data\\EventSubscriber\\RecordInitDoctrineEventListener'])) {
            return $container->privates['App\\Data\\EventSubscriber\\RecordInitDoctrineEventListener'];
        }

        return $container->privates['App\\Data\\EventSubscriber\\RecordInitDoctrineEventListener'] = new \App\Data\EventSubscriber\RecordInitDoctrineEventListener($a);
    }
}
