<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEmailHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Emails\LegacyHandler\SendEmailHandler' shared autowired service.
     *
     * @return \App\Emails\LegacyHandler\SendEmailHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/LegacyHandler/SendEmailHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/Service/RecordToEmailMapper/RecordToEmailService.php';
        include_once \dirname(__DIR__, 3).'/vendor/vich/uploader-bundle/src/Handler/AbstractHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Services/MediaObjectFileHandler.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Emails/LegacyHandler/Mailers/LegacyMailer.php';

        $a = ($container->privates['App\\FieldDefinitions\\LegacyHandler\\FieldDefinitionsHandler'] ?? $container->load('getFieldDefinitionsHandlerService'));

        if (isset($container->privates['App\\Emails\\LegacyHandler\\SendEmailHandler'])) {
            return $container->privates['App\\Emails\\LegacyHandler\\SendEmailHandler'];
        }
        $b = ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState());
        $c = ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack());
        $d = ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container));

        return $container->privates['App\\Emails\\LegacyHandler\\SendEmailHandler'] = new \App\Emails\LegacyHandler\SendEmailHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', $b, $c, $d, new \App\Emails\Service\RecordToEmailMapper\RecordToEmailService(($container->privates['App\\MediaObjects\\Repository\\DefaultMediaObjectManager'] ?? self::getDefaultMediaObjectManagerService($container)), $a, $d, new \App\MediaObjects\Services\MediaObjectFileHandler(($container->privates['vich_uploader.property_mapping_factory'] ?? self::getVichUploader_PropertyMappingFactoryService($container)), ($container->privates['vich_uploader.storage.flysystem'] ?? self::getVichUploader_Storage_FlysystemService($container)))), new \App\Emails\LegacyHandler\Mailers\LegacyMailer(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', $b, $c, $d));
    }
}
