<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchedulerCronLastRunStatisticService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Statistics\SchedulerCronLastRunStatistic' shared autowired service.
     *
     * @return \App\Schedulers\Statistics\SchedulerCronLastRunStatistic
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/Service/StatisticsProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/StatisticsHandlingTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Statistics/SchedulerCronLastRunStatistic.php';

        $a = ($container->privates['App\\Install\\Service\\CommandLastRunTracker'] ?? $container->load('getCommandLastRunTrackerService'));

        if (isset($container->privates['App\\Schedulers\\Statistics\\SchedulerCronLastRunStatistic'])) {
            return $container->privates['App\\Schedulers\\Statistics\\SchedulerCronLastRunStatistic'];
        }
        $b = ($container->services['app.cron.handler'] ?? $container->load('getApp_Cron_HandlerService'));

        if (isset($container->privates['App\\Schedulers\\Statistics\\SchedulerCronLastRunStatistic'])) {
            return $container->privates['App\\Schedulers\\Statistics\\SchedulerCronLastRunStatistic'];
        }

        return $container->privates['App\\Schedulers\\Statistics\\SchedulerCronLastRunStatistic'] = new \App\Schedulers\Statistics\SchedulerCronLastRunStatistic($a, $b);
    }
}
