<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendTestEmailHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Process\LegacyHandler\SendTestEmailHandler' shared autowired service.
     *
     * @return \App\Process\LegacyHandler\SendTestEmailHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Process/LegacyHandler/SendTestEmailHandler.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Log\\DefaultEmailCampaignLogManager'] ?? $container->load('getDefaultEmailCampaignLogManagerService'));

        if (isset($container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'])) {
            return $container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'];
        }
        $b = ($container->privates['App\\Emails\\LegacyHandler\\SendEmailHandler'] ?? $container->load('getSendEmailHandlerService'));

        if (isset($container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'])) {
            return $container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'];
        }
        $c = ($container->privates['App\\Emails\\LegacyHandler\\EmailProcessProcessor'] ?? $container->load('getEmailProcessProcessorService'));

        if (isset($container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'])) {
            return $container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'];
        }
        $d = ($container->privates['App\\Data\\LegacyHandler\\RecordHandler'] ?? $container->load('getRecordHandlerService'));

        if (isset($container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'])) {
            return $container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'];
        }
        $e = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\CampaignEmailParserManager'] ?? $container->load('getCampaignEmailParserManagerService'));

        if (isset($container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'])) {
            return $container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'];
        }
        $f = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\EmailTargetValidatorManager'] ?? $container->load('getEmailTargetValidatorManagerService'));

        if (isset($container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'])) {
            return $container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'];
        }

        return $container->privates['App\\Process\\LegacyHandler\\SendTestEmailHandler'] = new \App\Process\LegacyHandler\SendTestEmailHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, ($container->privates['App\\Emails\\LegacyHandler\\FilterEmailListHandler'] ?? $container->load('getFilterEmailListHandlerService')), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)), $b, ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')), $c, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $d, $e, $f);
    }
}
