<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShowSchedulersCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Command\ShowSchedulersCommand' shared autowired service.
     *
     * @return \App\Schedulers\Command\ShowSchedulersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Command/BaseCommand.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Command/ShowSchedulersCommand.php';

        $container->privates['App\\Schedulers\\Command\\ShowSchedulersCommand'] = $instance = new \App\Schedulers\Command\ShowSchedulersCommand(($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService')));

        $instance->setDefaultSessionName('SCRMSESSID');
        $instance->setLegacySessionName('SCRMSESSID');
        $instance->setRequestStack(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
        $instance->setAppStringsHandler(($container->privates['App\\Languages\\LegacyHandler\\AppStringsHandler'] ?? $container->load('getAppStringsHandlerService')));
        $instance->setCronHandler(($container->services['app.cron.handler'] ?? $container->load('getApp_Cron_HandlerService')));
        $instance->setLastRunTracker(($container->privates['App\\Install\\Service\\CommandLastRunTracker'] ?? $container->load('getCommandLastRunTrackerService')));
        $instance->setName('schedulers:show');

        return $instance;
    }
}
