<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEmailSchedulerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Service\Scheduler\Jobs\SendEmailScheduler' shared autowired service.
     *
     * @return \App\Schedulers\Service\Scheduler\Jobs\SendEmailScheduler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/SchedulerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Service/Scheduler/Jobs/SendEmailScheduler.php';

        return $container->privates['App\\Schedulers\\Service\\Scheduler\\Jobs\\SendEmailScheduler'] = new \App\Schedulers\Service\Scheduler\Jobs\SendEmailScheduler(($container->privates['App\\Module\\Campaigns\\Service\\Email\\Queue\\DefaultEmailQueueProcessor'] ?? $container->load('getDefaultEmailQueueProcessorService')));
    }
}
