<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchedulerCronSetupWidgetStatisticService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Schedulers\Statistics\SchedulerCronSetupWidgetStatistic' shared autowired service.
     *
     * @return \App\Schedulers\Statistics\SchedulerCronSetupWidgetStatistic
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/Service/StatisticsProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Statistics/StatisticsHandlingTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Schedulers/Statistics/SchedulerCronSetupWidgetStatistic.php';

        return $container->privates['App\\Schedulers\\Statistics\\SchedulerCronSetupWidgetStatistic'] = new \App\Schedulers\Statistics\SchedulerCronSetupWidgetStatistic(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
