<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackersEnabledRetrieveApiMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\Service\Fields\TrackersEnabledRetrieveApiMapper' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\Service\Fields\TrackersEnabledRetrieveApiMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseModuleMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/Mappers/BaseFieldMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Data/Service/Record/ApiRecordMappers/ApiRecordFieldMapperInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/EmailMarketing/Service/Fields/TrackersEnabledRetrieveApiMapper.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'] ?? $container->load('getDefaultEmailTrackerManagerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\TrackersEnabledRetrieveApiMapper'])) {
            return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\TrackersEnabledRetrieveApiMapper'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\Service\\Fields\\TrackersEnabledRetrieveApiMapper'] = new \App\Module\EmailMarketing\Service\Fields\TrackersEnabledRetrieveApiMapper($a);
    }
}
