<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadConstraintValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\MediaObjects\Validator\UploadValidator\UploadConstraintValidator' shared autowired service.
     *
     * @return \App\MediaObjects\Validator\UploadValidator\UploadConstraintValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Validator/UploadValidator/UploadConstraintValidator.php';
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Validator/UploadValidator/UploadValidatorRegistryInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Validator/UploadValidator/UploadValidatorRegistry.php';

        return $container->privates['App\\MediaObjects\\Validator\\UploadValidator\\UploadConstraintValidator'] = new \App\MediaObjects\Validator\UploadValidator\UploadConstraintValidator(new \App\MediaObjects\Validator\UploadValidator\UploadValidatorRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\MediaObjects\\Validator\\UploadValidator\\Validators\\BadExtensionUploadValidator'] ?? $container->load('getBadExtensionUploadValidatorService'));
            yield 1 => ($container->privates['App\\MediaObjects\\Validator\\UploadValidator\\Validators\\MaxFileSizeUploadValidator'] ?? $container->load('getMaxFileSizeUploadValidatorService'));
            yield 2 => ($container->privates['App\\MediaObjects\\Validator\\UploadValidator\\Validators\\SupportedImageTypeUploadValidator'] ?? $container->load('getSupportedImageTypeUploadValidatorService'));
        }, 3)), ($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')));
    }
}
