<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnsubscribeValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\EmailMarketing\LegacyHandler\Validation\Validators\UnsubscribeValidator' shared autowired service.
     *
     * @return \App\Module\EmailMarketing\LegacyHandler\Validation\Validators\UnsubscribeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Process/Service/ProcessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/EmailMarketing/LegacyHandler/Validation/Validators/UnsubscribeValidator.php';

        $a = ($container->privates['App\\Data\\LegacyHandler\\PreparedStatementHandler'] ?? $container->load('getPreparedStatementHandlerService'));

        if (isset($container->privates['App\\Module\\EmailMarketing\\LegacyHandler\\Validation\\Validators\\UnsubscribeValidator'])) {
            return $container->privates['App\\Module\\EmailMarketing\\LegacyHandler\\Validation\\Validators\\UnsubscribeValidator'];
        }

        return $container->privates['App\\Module\\EmailMarketing\\LegacyHandler\\Validation\\Validators\\UnsubscribeValidator'] = new \App\Module\EmailMarketing\LegacyHandler\Validation\Validators\UnsubscribeValidator($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
