<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUuidMediaObjectFileNamer_PrivateDocumentsMediaObjectService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\MediaObjects\Services\UuidMediaObjectFileNamer.private_documents_media_object' shared autowired service.
     *
     * @return \App\MediaObjects\Services\UuidMediaObjectFileNamer
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['App\\MediaObjects\\Services\\UuidMediaObjectFileNamer.private_documents_media_object'] = $container->createProxy('UuidMediaObjectFileNamerGhostB0adbfc', static fn () => \UuidMediaObjectFileNamerGhostB0adbfc::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).'/vendor/vich/uploader-bundle/src/Naming/NamerInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/MediaObjects/Services/UuidMediaObjectFileNamer.php';

        return $lazyLoad;
    }
}
