<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnsubscribeLinkParserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Parser\Parsers\UnsubscribeLinkParser' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Parser\Parsers\UnsubscribeLinkParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Parser/CampaignEmailParserInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Parser/Parsers/UnsubscribeLinkParser.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Targets\\DefaultEmailOptInManager'] ?? $container->load('getDefaultEmailOptInManagerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\UnsubscribeLinkParser'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\UnsubscribeLinkParser'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\UnsubscribeLinkParser'] = new \App\Module\Campaigns\Service\Email\Parser\Parsers\UnsubscribeLinkParser($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
