<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewedEmailTrackerParserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\Campaigns\Service\Email\Parser\Parsers\ViewedEmailTrackerParser' shared autowired service.
     *
     * @return \App\Module\Campaigns\Service\Email\Parser\Parsers\ViewedEmailTrackerParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Parser/CampaignEmailParserInterface.php';
        include_once \dirname(__DIR__, 3).'/core/modules/Campaigns/Service/Email/Parser/Parsers/ViewedEmailTrackerParser.php';

        $a = ($container->privates['App\\Module\\Campaigns\\Service\\Email\\Trackers\\DefaultEmailTrackerManager'] ?? $container->load('getDefaultEmailTrackerManagerService'));

        if (isset($container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\ViewedEmailTrackerParser'])) {
            return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\ViewedEmailTrackerParser'];
        }

        return $container->privates['App\\Module\\Campaigns\\Service\\Email\\Parser\\Parsers\\ViewedEmailTrackerParser'] = new \App\Module\Campaigns\Service\Email\Parser\Parsers\ViewedEmailTrackerParser($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
