<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVardefConfigMapperRegistryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\FieldDefinitions\Service\VardefConfigMapperRegistry' shared autowired service.
     *
     * @return \App\FieldDefinitions\Service\VardefConfigMapperRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['App\\FieldDefinitions\\Service\\VardefConfigMapperRegistry'] = $container->createProxy('VardefConfigMapperRegistryGhostD1f4222', static fn () => \VardefConfigMapperRegistryGhostD1f4222::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 3).'/core/backend/FieldDefinitions/Service/VardefConfigMapperRegistry.php';

        return ($lazyLoad->__construct(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\FieldDefinitions\\LegacyHandler\\DefaultMapper\\ParentTypeDefaultMapper'] ?? $container->load('getParentTypeDefaultMapperService'));
            yield 1 => ($container->privates['App\\Module\\Service\\Fields\\Attachments\\FieldDefinitions\\DisableDuplicationAttachmentsVardefMapper'] ??= new \App\Module\Service\Fields\Attachments\FieldDefinitions\DisableDuplicationAttachmentsVardefMapper());
            yield 2 => ($container->privates['App\\Module\\Service\\Fields\\File\\FieldDefinitions\\DisableDuplicationFileVardefMapper'] ??= new \App\Module\Service\Fields\File\FieldDefinitions\DisableDuplicationFileVardefMapper());
            yield 3 => ($container->privates['App\\Module\\EmailMarketing\\FieldDefinitions\\EmailMarketingTrackersEnabledMapper'] ?? $container->load('getEmailMarketingTrackersEnabledMapperService'));
        }, 4)) && false ?: $lazyLoad);
    }
}
