<?php

namespace ContainerPZYCc8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVichUploader_Form_Type_FileService extends App_KernelProdContainer
{
    /*
     * Gets the public 'vich_uploader.form.type.file' shared service.
     *
     * @return \Vich\UploaderBundle\Form\Type\VichFileType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 3).'/vendor/vich/uploader-bundle/src/Form/Type/VichFileType.php';

        return $container->services['vich_uploader.form.type.file'] = new \Vich\UploaderBundle\Form\Type\VichFileType(($container->privates['vich_uploader.storage.flysystem'] ?? self::getVichUploader_Storage_FlysystemService($container)), ($container->services['vich_uploader.upload_handler'] ?? $container->load('getVichUploader_UploadHandlerService')), ($container->privates['vich_uploader.property_mapping_factory'] ?? self::getVichUploader_PropertyMappingFactoryService($container)), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)));
    }
}
