#!/bin/bash

# SuiteCRM V7 to V8 Theme Asset Extraction Script
# Usage: ./extract-v7-assets.sh <v7-theme-directory> <output-directory>

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check arguments
if [ $# -ne 2 ]; then
    print_error "Usage: $0 <v7-theme-directory> <output-directory>"
    print_error "Example: $0 /path/to/v7-theme ./extracted-theme-assets"
    exit 1
fi

V7_THEME_DIR="$1"
OUTPUT_DIR="$2"

# Validate input directory
if [ ! -d "$V7_THEME_DIR" ]; then
    print_error "V7 theme directory does not exist: $V7_THEME_DIR"
    exit 1
fi

print_status "Starting SuiteCRM V7 to V8 theme asset extraction..."
print_status "Source: $V7_THEME_DIR"
print_status "Output: $OUTPUT_DIR"

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Initialize extraction
print_status "Creating directory structure..."
mkdir -p "$OUTPUT_DIR"/{assets/images,docs}

# Extract CSS/SCSS files
print_status "Extracting stylesheets..."
CSS_FILES=$(find "$V7_THEME_DIR" -name "*.css" -o -name "*.scss" 2>/dev/null || true)

if [ -n "$CSS_FILES" ]; then
    # Find main CSS file (usually the largest or named styles.css/main.css)
    MAIN_CSS=$(echo "$CSS_FILES" | grep -E "(styles?|main|theme)" | head -1)
    if [ -z "$MAIN_CSS" ]; then
        MAIN_CSS=$(echo "$CSS_FILES" | head -1)
    fi

    print_status "Main CSS file detected: $MAIN_CSS"

    # Extract CSS variables and create _variables.scss
    print_status "Extracting CSS variables..."
    cat > "$OUTPUT_DIR/_variables.scss" << 'EOF'
// SuiteCRM 8 Theme Variables - Extracted from V7 Theme
// Generated by extract-v7-assets.sh

// =============================================================================
// EXTRACTED COLORS (UPDATE THESE WITH YOUR ACTUAL VALUES)
// =============================================================================
$primary-color: #007bff;        // Update with your primary color
$secondary-color: #28a745;      // Update with your secondary color
$success-color: #28a745;
$warning-color: #ffc107;
$error-color: #dc3545;
$info-color: #17a2b8;

// =============================================================================
// GRAY SCALE (CUSTOMIZE AS NEEDED)
// =============================================================================
$gray-50: #f9f9f9;
$gray-100: #f8f9fa;
$gray-200: #e9ecef;
$gray-300: #dee2e6;
$gray-400: #ced4da;
$gray-500: #adb5bd;
$gray-600: #6c757d;
$gray-700: #495057;
$gray-800: #343a40;
$gray-900: #212529;

// =============================================================================
// TYPOGRAPHY
// =============================================================================
$font-family-base: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
$font-size-base: 14px;
$font-size-sm: 12px;
$font-size-lg: 16px;
$line-height-base: 1.5;

// =============================================================================
// SPACING
// =============================================================================
$space-xs: 4px;
$space-sm: 8px;
$space-md: 16px;
$space-lg: 24px;
$space-xl: 32px;

// =============================================================================
// BORDERS & SHADOWS
// =============================================================================
$border-radius-base: 6px;
$border-color: #dee2e6;
$shadow-sm: 0 2px 4px rgba(0,0,0,0.08);
$shadow-md: 0 4px 8px rgba(0,0,0,0.12);
$shadow-lg: 0 8px 16px rgba(0,0,0,0.16);

// =============================================================================
// TRANSITIONS
// =============================================================================
$transition-fast: 0.2s ease;
$transition-base: 0.3s ease;
EOF

    # Extract color values from CSS if possible
    if [ -f "$MAIN_CSS" ]; then
        print_status "Analyzing CSS for color values..."

        # Look for common color patterns and hex values
        COLORS=$(grep -oE '#[0-9A-Fa-f]{3,6}' "$MAIN_CSS" 2>/dev/null | sort | uniq || true)
        if [ -n "$COLORS" ]; then
            print_success "Found color values:"
            echo "$COLORS" | while read -r color; do
                echo "  $color"
            done

            # Update variables file with found colors
            print_status "Updating _variables.scss with detected colors..."
            echo "" >> "$OUTPUT_DIR/_variables.scss"
            echo "// ==============================================================================" >> "$OUTPUT_DIR/_variables.scss"
            echo "// DETECTED COLORS FROM V7 THEME" >> "$OUTPUT_DIR/_variables.scss"
            echo "// ==============================================================================" >> "$OUTPUT_DIR/_variables.scss"

            i=1
            echo "$COLORS" | while read -r color; do
                echo "\$detected-color-$i: $color;" >> "$OUTPUT_DIR/_variables.scss"
                ((i++))
            done
        fi
    fi
else
    print_warning "No CSS/SCSS files found in $V7_THEME_DIR"
fi

# Create _components.scss template
print_status "Creating component styles template..."
cat > "$OUTPUT_DIR/_components.scss" << 'EOF'
// SuiteCRM 8 Component Styles
// Extracted and adapted from V7 theme

// =============================================================================
// CARD COMPONENTS
// =============================================================================
@mixin card-base {
  background: white;
  border-radius: $border-radius-base;
  box-shadow: $shadow-sm;
  border: 1px solid $border-color;
  transition: $transition-fast;
}

.card {
  @include card-base;

  &:hover {
    box-shadow: $shadow-md;
    transform: translateY(-1px);
  }
}

// =============================================================================
// NAVIGATION
// =============================================================================
.nav-item {
  color: $gray-600;
  text-decoration: none;
  padding: 5px 10px;
  font-size: $font-size-sm;
  border-radius: $border-radius-base;
  transition: $transition-fast;

  &:hover {
    color: $primary-color;
    background-color: $gray-50;
  }

  &.active {
    color: $primary-color;
    font-weight: 600;
  }
}

// =============================================================================
// BUTTONS
// =============================================================================
.btn-primary {
  background-color: $primary-color;
  border-color: $primary-color;
  color: white;
  padding: 8px 16px;
  border-radius: $border-radius-base;
  transition: $transition-fast;

  &:hover {
    background-color: darken($primary-color, 10%);
    border-color: darken($primary-color, 10%);
  }
}

// =============================================================================
// TABLES
// =============================================================================
.data-table {
  width: 100%;
  border-collapse: collapse;

  th {
    background: $gray-100;
    padding: 10px;
    text-align: left;
    border-bottom: 1px solid $border-color;
    color: $gray-700;
    font-weight: 500;
  }

  td {
    padding: 10px;
    border-bottom: 1px solid $border-color;
    color: $gray-800;
  }

  tr:hover {
    background: $gray-50;
  }
}
EOF

# Create _typography.scss
print_status "Creating typography styles..."
cat > "$OUTPUT_DIR/_typography.scss" << 'EOF'
// SuiteCRM 8 Typography System

// =============================================================================
// BASE TYPOGRAPHY
// =============================================================================
body {
  font-family: $font-family-base;
  font-size: $font-size-base;
  line-height: $line-height-base;
  color: $gray-800;
}

// =============================================================================
// UTILITY CLASSES
// =============================================================================
.text-primary { color: $primary-color; }
.text-secondary { color: $secondary-color; }
.text-success { color: $success-color; }
.text-warning { color: $warning-color; }
.text-danger { color: $error-color; }

.text-sm { font-size: $font-size-sm; }
.text-lg { font-size: $font-size-lg; }

.font-weight-normal { font-weight: 400; }
.font-weight-medium { font-weight: 500; }
.font-weight-semibold { font-weight: 600; }
.font-weight-bold { font-weight: 700; }

// =============================================================================
// ANIMATIONS
// =============================================================================
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}

.fade-in {
  animation: fadeIn 0.3s ease-in-out;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.7; }
}

.pulse {
  animation: pulse 2s infinite;
}
EOF

# Create main.scss
print_status "Creating main SCSS file..."
cat > "$OUTPUT_DIR/main.scss" << 'EOF'
// SuiteCRM 8 Theme - Main Stylesheet
// Import order is important

@import 'variables';      // Colors, spacing, typography tokens
@import 'typography';     // Text styles and animations
@import 'components';     // UI components and layouts

// =============================================================================
// GLOBAL STYLES
// =============================================================================
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

// =============================================================================
// SUITECRM 8 COMPATIBILITY OVERRIDES
// =============================================================================
:root {
  --primary-color: #{$primary-color} !important;
  --secondary-color: #{$secondary-color} !important;
  --success-color: #{$success-color} !important;
  --warning-color: #{$warning-color} !important;
  --error-color: #{$error-color} !important;
  --text-color: #{$gray-800} !important;
  --text-color-secondary: #{$gray-600} !important;
  --surface-ground: #{$gray-100} !important;
  --surface-section: #ffffff !important;
  --surface-card: #ffffff !important;
}

// Angular component compatibility
.p-component {
  font-family: $font-family-base !important;
}

.p-button-primary {
  background-color: $primary-color !important;
  border-color: $primary-color !important;
}

.p-datatable .p-datatable-thead th {
  background: $gray-100 !important;
  color: $gray-700 !important;
}

// Links
a:not(.p-button) {
  color: $primary-color !important;

  &:hover {
    color: darken($primary-color, 15%) !important;
  }
}
EOF

# Copy images and assets
print_status "Copying image assets..."
IMAGES_FOUND=0
for ext in png jpg jpeg gif svg ico; do
    FILES=$(find "$V7_THEME_DIR" -name "*.$ext" 2>/dev/null || true)
    if [ -n "$FILES" ]; then
        echo "$FILES" | while read -r file; do
            if [ -f "$file" ]; then
                filename=$(basename "$file")
                cp "$file" "$OUTPUT_DIR/assets/images/"
                print_success "Copied image: $filename"
                IMAGES_FOUND=1
            fi
        done
    fi
done

if [ $IMAGES_FOUND -eq 0 ]; then
    print_warning "No image assets found to copy"
fi

# Create documentation
print_status "Creating documentation..."
cat > "$OUTPUT_DIR/README.md" << EOF
# Extracted Theme Assets

This directory contains the extracted assets from your SuiteCRM V7 theme.

## Generated Files

### SCSS Files
- \`_variables.scss\` - Color scheme, spacing, typography variables
- \`_components.scss\` - UI component styles (cards, buttons, tables, navigation)
- \`_typography.scss\` - Text styling, animations, utility classes
- \`main.scss\` - Main import file with SuiteCRM 8 compatibility overrides

### Assets
- \`assets/images/\` - Copied image files from V7 theme

## Next Steps

1. **Review Variables**: Update \`_variables.scss\` with your actual color values
2. **Customize Components**: Modify \`_components.scss\` to match your V7 styling
3. **Import to Extension**: Copy these files to your SuiteCRM 8 extension
4. **Test & Refine**: Deploy and test, making adjustments as needed

## Integration Instructions

Copy these files to your SuiteCRM 8 extension:

\`\`\`bash
cp -r ./* /path/to/suitecrm8/extensions/your-theme/app/src/theme-assets/
\`\`\`

Update your extension's \`styles.scss\`:

\`\`\`scss
@import './theme-assets/main';
\`\`\`

## Color Values Detected

EOF

# Add detected colors to documentation
if [ -n "$COLORS" ]; then
    echo "The following colors were detected in your V7 theme:" >> "$OUTPUT_DIR/README.md"
    echo "" >> "$OUTPUT_DIR/README.md"
    echo "$COLORS" | while read -r color; do
        echo "- \`$color\`" >> "$OUTPUT_DIR/README.md"
    done
    echo "" >> "$OUTPUT_DIR/README.md"
    echo "**Action Required**: Update the color variables in \`_variables.scss\` with these values." >> "$OUTPUT_DIR/README.md"
else
    echo "No color values were automatically detected. Please manually update \`_variables.scss\`." >> "$OUTPUT_DIR/README.md"
fi

cat >> "$OUTPUT_DIR/README.md" << EOF

## Manual Review Required

Please review and customize the following:

1. **Color Variables**: Ensure all colors in \`_variables.scss\` match your brand
2. **Typography**: Verify font families and sizes are correct
3. **Component Styles**: Adapt component styling to match your V7 theme
4. **Spacing**: Adjust spacing values to match your layout
5. **Images**: Verify all necessary images were copied

## Extraction Summary

- **Source Directory**: $V7_THEME_DIR
- **Extraction Date**: $(date)
- **CSS Files Processed**: $(echo "$CSS_FILES" | wc -l)
- **Images Copied**: $(find "$OUTPUT_DIR/assets/images" -type f 2>/dev/null | wc -l)

EOF

# Create extraction log
cat > "$OUTPUT_DIR/extraction.log" << EOF
SuiteCRM V7 to V8 Theme Asset Extraction Log
Generated: $(date)
Source: $V7_THEME_DIR
Output: $OUTPUT_DIR

Files Processed:
EOF

if [ -n "$CSS_FILES" ]; then
    echo "$CSS_FILES" >> "$OUTPUT_DIR/extraction.log"
fi

# Final summary
print_success "Theme asset extraction completed successfully!"
echo ""
print_status "Summary:"
echo "  📁 Output directory: $OUTPUT_DIR"
echo "  📝 SCSS files created: 4"
echo "  🖼️  Images copied: $(find "$OUTPUT_DIR/assets/images" -type f 2>/dev/null | wc -l || echo "0")"
echo "  📋 Documentation: README.md"
echo ""
print_status "Next steps:"
echo "  1. Review and update _variables.scss with your actual colors"
echo "  2. Customize component styles in _components.scss"
echo "  3. Copy assets to your SuiteCRM 8 extension"
echo "  4. Import main.scss in your extension's styles.scss"
echo ""
print_success "Extraction complete! Check $OUTPUT_DIR for all extracted files."