<?php

namespace Proxies\__CG__\App\MediaObjects\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArchivedDocumentMediaObject extends \App\MediaObjects\Entity\ArchivedDocumentMediaObject implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'assignedUserId' => [parent::class, 'assignedUserId', null],
        'contentUrl' => [parent::class, 'contentUrl', null],
        'createdBy' => [parent::class, 'createdBy', null],
        'dateEntered' => [parent::class, 'dateEntered', null],
        'dateModified' => [parent::class, 'dateModified', null],
        'deleted' => [parent::class, 'deleted', null],
        'description' => [parent::class, 'description', null],
        'dimensions' => [parent::class, 'dimensions', null],
        'file' => [parent::class, 'file', null],
        'filePath' => [parent::class, 'filePath', null],
        'id' => [parent::class, 'id', null],
        'mimeType' => [parent::class, 'mimeType', null],
        'modifiedUserId' => [parent::class, 'modifiedUserId', null],
        'name' => [parent::class, 'name', null],
        'originalName' => [parent::class, 'originalName', null],
        'parentField' => [parent::class, 'parentField', null],
        'parentId' => [parent::class, 'parentId', null],
        'parentType' => [parent::class, 'parentType', null],
        'size' => [parent::class, 'size', null],
        'temporary' => [parent::class, 'temporary', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
