[PHP]
memory_limit = 512M
max_execution_time = 300
upload_max_filesize = 30M
post_max_size = 30M
date.timezone = UTC
error_log = /var/www/html/logs/php-errors.log
log_errors = On
display_errors = Off
sys_temp_dir = /var/www/html/cache/tmp
upload_tmp_dir = /var/www/html/cache/tmp
